//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.12.0
//     from Assets/Scripts/BuildingSystem/BuildManager/BuildActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/BuildingSystem/BuildManager/BuildActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @BuildActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @BuildActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""BuildActions"",
    ""maps"": [
        {
            ""name"": ""PreviewMode"",
            ""id"": ""3e21666f-7a8e-42f4-aa25-1df6f6fbf7f3"",
            ""actions"": [
                {
                    ""name"": ""PlaceAction"",
                    ""type"": ""Button"",
                    ""id"": ""b6abe3dc-bc7d-4bb5-bb4a-03d15dd7e07d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExitBuildMode"",
                    ""type"": ""Button"",
                    ""id"": ""e81c3523-f785-4344-a7e6-96c749e51b25"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateBuilding"",
                    ""type"": ""Button"",
                    ""id"": ""38e79f5a-771b-4144-95bc-d8b47c9e4d7e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""93bac52b-ebba-4414-9cce-cccce31863b3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""263ae0db-ce65-45f0-b434-f796019becd3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExitBuildMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c35b44f-1ab0-4bc4-92be-d3d284464a6f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateBuilding"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PreviewMode
        m_PreviewMode = asset.FindActionMap("PreviewMode", throwIfNotFound: true);
        m_PreviewMode_PlaceAction = m_PreviewMode.FindAction("PlaceAction", throwIfNotFound: true);
        m_PreviewMode_ExitBuildMode = m_PreviewMode.FindAction("ExitBuildMode", throwIfNotFound: true);
        m_PreviewMode_RotateBuilding = m_PreviewMode.FindAction("RotateBuilding", throwIfNotFound: true);
    }

    ~@BuildActions()
    {
        UnityEngine.Debug.Assert(!m_PreviewMode.enabled, "This will cause a leak and performance issues, BuildActions.PreviewMode.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PreviewMode
    private readonly InputActionMap m_PreviewMode;
    private List<IPreviewModeActions> m_PreviewModeActionsCallbackInterfaces = new List<IPreviewModeActions>();
    private readonly InputAction m_PreviewMode_PlaceAction;
    private readonly InputAction m_PreviewMode_ExitBuildMode;
    private readonly InputAction m_PreviewMode_RotateBuilding;
    /// <summary>
    /// Provides access to input actions defined in input action map "PreviewMode".
    /// </summary>
    public struct PreviewModeActions
    {
        private @BuildActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PreviewModeActions(@BuildActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PreviewMode/PlaceAction".
        /// </summary>
        public InputAction @PlaceAction => m_Wrapper.m_PreviewMode_PlaceAction;
        /// <summary>
        /// Provides access to the underlying input action "PreviewMode/ExitBuildMode".
        /// </summary>
        public InputAction @ExitBuildMode => m_Wrapper.m_PreviewMode_ExitBuildMode;
        /// <summary>
        /// Provides access to the underlying input action "PreviewMode/RotateBuilding".
        /// </summary>
        public InputAction @RotateBuilding => m_Wrapper.m_PreviewMode_RotateBuilding;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PreviewMode; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PreviewModeActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PreviewModeActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PreviewModeActions" />
        public void AddCallbacks(IPreviewModeActions instance)
        {
            if (instance == null || m_Wrapper.m_PreviewModeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PreviewModeActionsCallbackInterfaces.Add(instance);
            @PlaceAction.started += instance.OnPlaceAction;
            @PlaceAction.performed += instance.OnPlaceAction;
            @PlaceAction.canceled += instance.OnPlaceAction;
            @ExitBuildMode.started += instance.OnExitBuildMode;
            @ExitBuildMode.performed += instance.OnExitBuildMode;
            @ExitBuildMode.canceled += instance.OnExitBuildMode;
            @RotateBuilding.started += instance.OnRotateBuilding;
            @RotateBuilding.performed += instance.OnRotateBuilding;
            @RotateBuilding.canceled += instance.OnRotateBuilding;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PreviewModeActions" />
        private void UnregisterCallbacks(IPreviewModeActions instance)
        {
            @PlaceAction.started -= instance.OnPlaceAction;
            @PlaceAction.performed -= instance.OnPlaceAction;
            @PlaceAction.canceled -= instance.OnPlaceAction;
            @ExitBuildMode.started -= instance.OnExitBuildMode;
            @ExitBuildMode.performed -= instance.OnExitBuildMode;
            @ExitBuildMode.canceled -= instance.OnExitBuildMode;
            @RotateBuilding.started -= instance.OnRotateBuilding;
            @RotateBuilding.performed -= instance.OnRotateBuilding;
            @RotateBuilding.canceled -= instance.OnRotateBuilding;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PreviewModeActions.UnregisterCallbacks(IPreviewModeActions)" />.
        /// </summary>
        /// <seealso cref="PreviewModeActions.UnregisterCallbacks(IPreviewModeActions)" />
        public void RemoveCallbacks(IPreviewModeActions instance)
        {
            if (m_Wrapper.m_PreviewModeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PreviewModeActions.AddCallbacks(IPreviewModeActions)" />
        /// <seealso cref="PreviewModeActions.RemoveCallbacks(IPreviewModeActions)" />
        /// <seealso cref="PreviewModeActions.UnregisterCallbacks(IPreviewModeActions)" />
        public void SetCallbacks(IPreviewModeActions instance)
        {
            foreach (var item in m_Wrapper.m_PreviewModeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PreviewModeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PreviewModeActions" /> instance referencing this action map.
    /// </summary>
    public PreviewModeActions @PreviewMode => new PreviewModeActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PreviewMode" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PreviewModeActions.AddCallbacks(IPreviewModeActions)" />
    /// <seealso cref="PreviewModeActions.RemoveCallbacks(IPreviewModeActions)" />
    public interface IPreviewModeActions
    {
        /// <summary>
        /// Method invoked when associated input action "PlaceAction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPlaceAction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ExitBuildMode" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnExitBuildMode(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RotateBuilding" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotateBuilding(InputAction.CallbackContext context);
    }
}
