//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.12.0
//     from Assets/Scripts/InputActions/WeaponInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/InputActions/WeaponInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @WeaponInputAction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @WeaponInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""WeaponInputActions"",
    ""maps"": [
        {
            ""name"": ""WeaponInputActions"",
            ""id"": ""f8965fbc-a0cb-42b4-ad93-b757cf19b42e"",
            ""actions"": [
                {
                    ""name"": ""RotateArtillery"",
                    ""type"": ""Button"",
                    ""id"": ""db5aaf7f-bd50-4611-84b0-e934381b328e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AdjustCannonAngle"",
                    ""type"": ""Button"",
                    ""id"": ""28dab4ad-39b6-4981-b8bf-f926308543b8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExitFightMode"",
                    ""type"": ""Button"",
                    ""id"": ""a5c9cb25-94d5-4119-9698-a554d4ee842e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FireCannon"",
                    ""type"": ""Button"",
                    ""id"": ""507b0636-3e2b-451f-8580-0eef840fc67d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""da103b83-4b68-490c-bc21-88d898d25ed8"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExitFightMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""9dbb4186-a9fc-4380-ac59-8fb37d666495"",
                    ""path"": ""1DAxis"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateArtillery"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""cb9458d6-f801-40a0-98af-1f7db7ccfa38"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateArtillery"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""20cd3c0f-37a3-44b7-94d1-d387968566b7"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateArtillery"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""d9f49a42-9a49-4222-b039-d68778daa85b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AdjustCannonAngle"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Positive"",
                    ""id"": ""c2592589-1028-4ff6-834e-ada4a3b17d4e"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AdjustCannonAngle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Negative"",
                    ""id"": ""90c7cfd0-96af-4dcf-809f-4656a4389c85"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AdjustCannonAngle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3ac79c99-b45d-4f88-8a62-81303297844d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FireCannon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // WeaponInputActions
        m_WeaponInputActions = asset.FindActionMap("WeaponInputActions", throwIfNotFound: true);
        m_WeaponInputActions_RotateArtillery = m_WeaponInputActions.FindAction("RotateArtillery", throwIfNotFound: true);
        m_WeaponInputActions_AdjustCannonAngle = m_WeaponInputActions.FindAction("AdjustCannonAngle", throwIfNotFound: true);
        m_WeaponInputActions_ExitFightMode = m_WeaponInputActions.FindAction("ExitFightMode", throwIfNotFound: true);
        m_WeaponInputActions_FireCannon = m_WeaponInputActions.FindAction("FireCannon", throwIfNotFound: true);
    }

    ~@WeaponInputAction()
    {
        UnityEngine.Debug.Assert(!m_WeaponInputActions.enabled, "This will cause a leak and performance issues, WeaponInputAction.WeaponInputActions.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // WeaponInputActions
    private readonly InputActionMap m_WeaponInputActions;
    private List<IWeaponInputActionsActions> m_WeaponInputActionsActionsCallbackInterfaces = new List<IWeaponInputActionsActions>();
    private readonly InputAction m_WeaponInputActions_RotateArtillery;
    private readonly InputAction m_WeaponInputActions_AdjustCannonAngle;
    private readonly InputAction m_WeaponInputActions_ExitFightMode;
    private readonly InputAction m_WeaponInputActions_FireCannon;
    /// <summary>
    /// Provides access to input actions defined in input action map "WeaponInputActions".
    /// </summary>
    public struct WeaponInputActionsActions
    {
        private @WeaponInputAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public WeaponInputActionsActions(@WeaponInputAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "WeaponInputActions/RotateArtillery".
        /// </summary>
        public InputAction @RotateArtillery => m_Wrapper.m_WeaponInputActions_RotateArtillery;
        /// <summary>
        /// Provides access to the underlying input action "WeaponInputActions/AdjustCannonAngle".
        /// </summary>
        public InputAction @AdjustCannonAngle => m_Wrapper.m_WeaponInputActions_AdjustCannonAngle;
        /// <summary>
        /// Provides access to the underlying input action "WeaponInputActions/ExitFightMode".
        /// </summary>
        public InputAction @ExitFightMode => m_Wrapper.m_WeaponInputActions_ExitFightMode;
        /// <summary>
        /// Provides access to the underlying input action "WeaponInputActions/FireCannon".
        /// </summary>
        public InputAction @FireCannon => m_Wrapper.m_WeaponInputActions_FireCannon;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_WeaponInputActions; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="WeaponInputActionsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(WeaponInputActionsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="WeaponInputActionsActions" />
        public void AddCallbacks(IWeaponInputActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_WeaponInputActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_WeaponInputActionsActionsCallbackInterfaces.Add(instance);
            @RotateArtillery.started += instance.OnRotateArtillery;
            @RotateArtillery.performed += instance.OnRotateArtillery;
            @RotateArtillery.canceled += instance.OnRotateArtillery;
            @AdjustCannonAngle.started += instance.OnAdjustCannonAngle;
            @AdjustCannonAngle.performed += instance.OnAdjustCannonAngle;
            @AdjustCannonAngle.canceled += instance.OnAdjustCannonAngle;
            @ExitFightMode.started += instance.OnExitFightMode;
            @ExitFightMode.performed += instance.OnExitFightMode;
            @ExitFightMode.canceled += instance.OnExitFightMode;
            @FireCannon.started += instance.OnFireCannon;
            @FireCannon.performed += instance.OnFireCannon;
            @FireCannon.canceled += instance.OnFireCannon;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="WeaponInputActionsActions" />
        private void UnregisterCallbacks(IWeaponInputActionsActions instance)
        {
            @RotateArtillery.started -= instance.OnRotateArtillery;
            @RotateArtillery.performed -= instance.OnRotateArtillery;
            @RotateArtillery.canceled -= instance.OnRotateArtillery;
            @AdjustCannonAngle.started -= instance.OnAdjustCannonAngle;
            @AdjustCannonAngle.performed -= instance.OnAdjustCannonAngle;
            @AdjustCannonAngle.canceled -= instance.OnAdjustCannonAngle;
            @ExitFightMode.started -= instance.OnExitFightMode;
            @ExitFightMode.performed -= instance.OnExitFightMode;
            @ExitFightMode.canceled -= instance.OnExitFightMode;
            @FireCannon.started -= instance.OnFireCannon;
            @FireCannon.performed -= instance.OnFireCannon;
            @FireCannon.canceled -= instance.OnFireCannon;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="WeaponInputActionsActions.UnregisterCallbacks(IWeaponInputActionsActions)" />.
        /// </summary>
        /// <seealso cref="WeaponInputActionsActions.UnregisterCallbacks(IWeaponInputActionsActions)" />
        public void RemoveCallbacks(IWeaponInputActionsActions instance)
        {
            if (m_Wrapper.m_WeaponInputActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="WeaponInputActionsActions.AddCallbacks(IWeaponInputActionsActions)" />
        /// <seealso cref="WeaponInputActionsActions.RemoveCallbacks(IWeaponInputActionsActions)" />
        /// <seealso cref="WeaponInputActionsActions.UnregisterCallbacks(IWeaponInputActionsActions)" />
        public void SetCallbacks(IWeaponInputActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_WeaponInputActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_WeaponInputActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="WeaponInputActionsActions" /> instance referencing this action map.
    /// </summary>
    public WeaponInputActionsActions @WeaponInputActions => new WeaponInputActionsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "WeaponInputActions" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="WeaponInputActionsActions.AddCallbacks(IWeaponInputActionsActions)" />
    /// <seealso cref="WeaponInputActionsActions.RemoveCallbacks(IWeaponInputActionsActions)" />
    public interface IWeaponInputActionsActions
    {
        /// <summary>
        /// Method invoked when associated input action "RotateArtillery" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotateArtillery(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "AdjustCannonAngle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAdjustCannonAngle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ExitFightMode" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnExitFightMode(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FireCannon" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFireCannon(InputAction.CallbackContext context);
    }
}
