on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add issue to project using GitHub CLI
        run: |
          gh project item-add 2 --owner PM4-FS25-FortressForge --url ${{ github.event.issue.html_url }}
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
