name: Unity Build

on:
  push:    # Runs on any push to any branch
  pull_request:  # Runs on any PR to any branch
  workflow_dispatch:  # Allows manual execution from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # Change to windows-latest if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Set Up Unity License
        run: |
          mkdir -p $HOME/.unity
          echo "$UNITY_LICENSE" | base64 --decode > $HOME/.unity/Unity.ulf
          echo "License file created at: $HOME/.unity/Unity.ulf"
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Build Unity Project
        uses: game-ci/unity-builder@v4.3.0
        with:
          unityVersion: 6000.0.37f  # Change to your actual Unity version
          targetPlatform: StandaloneWindows64
          projectPath: .  # Adjust if Unity project is in a subfolder
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnityBuild
          path: build/StandaloneWindows64  # Change based on the platform
