name: Unity Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      clean:
        description: 'Cleans the library folder and deletes cached items'
        required: false
        default: false
        type: 'boolean'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.event.action == 'synchronize' }}

jobs:
  test:
    name: Run Unity Tests
    env:
      UNITY_PROJECT_PATH: ''
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: ${{ github.event.inputs.clean == 'true' }}
      - name: Activate Unity License
        uses: game-ci/unity-activate@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      - name: Run Edit Mode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          testMode: editMode
      - name: Run Play Mode Tests
        uses: game-ci/unity-test-runner@v4
        with:
          testMode: playMode
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: test-results

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          clean: ${{ github.event.inputs.clean == 'true' }}
      - name: Activate Unity License
        uses: game-ci/unity-activate@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      - name: Build Project
        uses: game-ci/unity-builder@v4.3.0
        with:
          targetPlatform: StandaloneWindows64
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: build